#!/bin/sh
#
#  Reused from the StackOverflow article.  Solution by Dennis Williamson
#
set -x
for file in /etc/local/runonce.d/*
do
    if [ ! -f "$file" ]
    then
        continue
    fi
    mv "$file" ran 
    /etc/local/runonce.d/ran/`basename $file` |& tee /tmp/`basename $file`.log
    logger -t runonce -p local3.info "$fullFile"
done
